name: dieta_insieme
description: App per visualizzare e confrontare diete personalizzate
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  
  # State Management
  provider: ^6.1.1
  
  # Gemini AI
  google_generative_ai: ^0.4.7
  
  # File handling
  file_picker: ^10.3.8
  path_provider: ^2.1.2
  
  # Storage
  shared_preferences: ^2.2.2
  
  # Charts
  fl_chart: ^0.68.0

  # Utils
  intl: ^0.18.1
  collection: ^1.18.0
  flutter_markdown: ^0.7.7+1
  share_plus: ^12.0.1
  image_picker: ^1.2.1
  receive_sharing_intent: ^1.8.1
  mime: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  
  assets:
    - assets/pdf_input/
